train_path: data/train.csv
test_path: data/test.csv
libmultilabel_test_path: output/libmultilabel-test.txt
predict_path: output/predictions.txt # path to `predictions.txt`
ranker: NLIClassifier
output_path: output/binary_classifcation_test.csv